package.json, rollup.config.js, rollup.demo.config.js, src/cellselection.js, src/columnresizing.js, src/commands.js, src/copypaste.js, src/fixtables.js, src/index.js, src/input.js, src/schema.js, src/tablemap.js, src/tableview.js, src/util.js, test/build.js, test/test-cellselection.js, test/test-commands.js, test/test-copypaste.js, test/test-fixtable.js, test/test-tablemap.js
=> Use ES6 sources and rollup for building

src/columnresizing.js
Older browsers complain about it.
=> Fix function nested in if block

src/util.js
If `sel.$anchorCell` is truthy, the if block will execute and the function will return on line 24.
=> Remove logic redundancy

src/util.js
Looks like a copy/paste mistake.
=> Fix bug in cellNear

src/commands.js, src/index.js
addColumn/addRow needed to change table without manipulating selection.
inSameTable needed to enable/disable table features on selection change.
=> Expose useful table functions

README.md
Added instructions to get started for people not familiar with npm.
=> updated README with getting started instructions

src/commands.js, src/util.js, test/test-commands.js
=> Fix for splitting of table header cells.

src/cellselection.js
Implementation based on discussion in #53
=> Return the table if all cells are selected in a cell selection

src/cellselection.js
=> Normalize a text selection that ends at the start of the next cell

src/columnresizing.js
=> fix column resizing when cells have nodeView

src/commands.js, test/test-commands.js
=> fix mergeCells when selection spans multiple rows

index.d.ts, package-lock.json, package.json, test/test-typescript.js, test/typescript/prosemirror-tables.ts, test/typescript/tsconfig.json
Move typescript definition from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository to the project.
This would help to prevent releases of **prosemirror-tables** before the type is updated in DefinitelyTyped repository.
This has been done in similar way for packages like **redux**.
=> Move typescript definition file into the project

index.d.ts, src/fixtables.js, src/index.js
Avoid misbehavior with `createSelectionBetween`
=> Add fixTablesKey on fixTable metadata transaction

index.d.ts, src/commands.js
Exposing these functions so I can use in my own commands.
=> Export more command functions

.eslintrc.json, .gitignore, demo/demo.ts, package.json, src/cellselection.ts, src/columnresizing.ts, src/commands.ts, src/copypaste.ts, src/fixtables.ts, src/index.ts, src/input.ts, src/schema.ts, src/tablemap.ts, src/tableview.ts, src/util.ts, test/build.ts, test/cellselection.test.ts, test/column-resizing.test.ts, test/commands.test.ts, test/copypaste.test.ts, test/fixtable.test.ts, test/tablemap.test.ts, tsconfig.json, yarn.lock
This PR sets the `strict` as `true` in `tsconfig.json`, along with some tiny changes for internal API interface.
=> Use strict typescript config

tsup.config.ts
Close https://github.com/ProseMirror/prosemirror-tables/issues/192
=> Set build target to ES2018

src/columnresizing.ts
The original pull request link address is https://github.com/ProseMirror/prosemirror-tables/pull/99
=> Fix finicky resize handle

src/columnresizing.ts
when editor content placed into iframe, handlers not working
=> Don't use global window

src/columnresizing.ts
=> Reflect internal col variable calculation

.github/actions/setup/action.yml, .github/workflows/release.yaml
Closes https://github.com/ProseMirror/prosemirror-tables/issues/237
=> ci: add release workflow

package.json, pnpm-lock.yaml, src/tableview.ts
Closes https://github.com/ProseMirror/prosemirror-tables/issues/258
=> fix: update prosemirror dependencies and fix type of ignoreMutation

src/schema.ts
Closes https://github.com/ProseMirror/prosemirror-tables/issues/285
=> fix: fix validate for attribute colwidth
