demo.js
index.html
package.json

This upgrades some things and changes the way plugins are ordered so that the gapcursor plugin works in the demo.

Make the gapcursor work properly in the demo

---

README.md
package.json
src/README.md
src/cellselection.js
src/commands.js
src/copypaste.js
src/fixtables.js
src/index.js
src/schema.js
src/tablemap.js

This uses [builddocs](https://github.com/marijnh/builddocs) to extract doc comments from the code and build a README with API docs -- making it easier to keep the doc comments and the README in sync. It means that editing the README should now be done in `src/README.md`, which is a template from which the top README.md is generated.
Would this work for you or do you have a preferred tool/process for this?

Use builddocs to put the API docs in the readme

---

demo.js
index.html
src/cellselection.js
src/columnresizing.js
src/commands.js
src/copypaste.js
src/fixtables.js
src/index.js
src/schema.js
src/tablemap.js
src/tableview.js
src/util.js
style/tables.css
test/test-cellselection.js
test/test-commands.js
test/test-copypaste.js
test/test-fixtable.js

This pull request does several things:
- It add an attribute `colwidth` to table cells, which stores the width of the columns that the cell if part of. Each column can have either no fixed with or a width in pixels.
I ended up storing this on the cells instead of the table because it makes it easier to make sure that a given width 'sticks' to the right column when the table is modified, and when cells are moved around. The table-fixing code makes sure column widths stay coherent by adjusting widths in the same column to the width of the majority of that column
- It introduces a new plugin `columnResizing` which implements a table view that renders and updates `<col>` tags for tables to specify the column widths, and functionality for resize handles on column boundaries.
(I ended up …

Add a plugin for column-resizing

---

src/input.js

This addresses the issue of having the editor 'stuck' in cell-selecting mode though the mouse button was released when you dragged a cell selection.
Issue #8

Stop cell-selecting when a dragstart event occurs

---

demo.js
src/fixtables.js

It'll make it impossible to fully undo the changes that triggered the
fix.
Issue #8

Don't disable history when fixing up tables

---

src/util.js

To avoid returning null for odd selections inside tables.

Fall back to cellNear in selectionCell

---

src/schema.js

So that people can use this with the next release of prosemirror-gapcursor without problems. (See [this patch](https://github.com/ProseMirror/prosemirror-gapcursor/commit/89bb7d7304730f9da02252ba7950b591de99db34)).

Add flags to disable gap cursors inside table and row nodes

---

src/util.js

Fixes broken test: addColumnAfter properly handles a cell node selection

Treat node selections of table cells similar to cell selections

---

src/cellselection.js

This implements the change proposed in #44.
(If you merge it, releasing a 0.7.0 would be much appreciated.)

Fix names of CellSelection.colSelection and CellSelection.rowSelection

---

src/input.js

This avoids a problem where putting this plugin before prosemirror-gapcursor in the plugin list breaks gap cursors when leaving a table at the start or end of the document, because the plugin's key handlers return true and don't give further plugins a chance to handle the events.

Make sure key handlers return false when they have no effect

---

src/columnresizing.js

Before, the plugin would abort the resize as soon as you hit the edge of the editor. With the change, the drag's effect goes through as you'd expect.

Make dragging column borders past the end of the editor work

---

src/commands.js
src/util.js
test/test-commands.js

Currently its not possible to split spanning cell with cursor in it. PR fixes this issue.

It should be possible to split col or row spanning cell which has cursor but not cell-selection.

---

README.md

This is essentially the same commit as https://github.com/ProseMirror/prosemirror-schema-table/commit/57c170f2c39e2e7b75d6d72bf766409cf867ffc4 by @marijnh
The rationale behind this is discussed in ProseMirror/prosemirror#432
This closes #22

Document Firefox's table UI controls problem

---

src/fixtables.js
test/test-fixtable.js

Currently `fixTable` will always inserts a `cell` when trying to patch a table, instead this looks at the current row's role and tries to match it.

Respect tableRole when fixing a table

---

src/commands.js
test/test-commands.js

This PR revers changes made in https://github.com/ProseMirror/prosemirror-tables/pull/69
This fix was unnecessary and currently it gets in a way of fixing the problem in our application.

Revert changes made in pr #69

---

README.md
src/cellselection.js
src/index.js
test/test-cellselection.js

Adds the option `allowTableNodeSelection` to the `tableEditing` plugin. When this option is set to `true`, the selection normalization routine will not convert a `NodeSelection`  of the table node to a `CellSelection` of all cells in the table.
Includes four new unit tests for the normalization of node selections.
Addresses #53

Add option to allow table node selection.

---

README.md
src/README.md
src/commands.js
test/test-commands.js

The current implementation has a few bugs and a misunderstand on the implementation, this new logic will fix the bugs and bring a new approach about how we deal with toggleHeaders.
the current deprecated behavior:
with the new logic `toggleHeader('column')` this is the result:
For now we are keeping the functions `toggleHeaderRow,toggleHeaderColumn and toggleHeaderCell` using the deprecated logic, until next major release. To use the new logic you should you the `toggleHeader` directly.
| BEFORE        | AFTER           |
| ------------- |:-------------:| 
| ![Screen Recording 2019-05-03 at 03 55 pm](https://user-images.githubusercontent.com/3452187/57121593-fd731380-6dbb-11e9-9619-98b3dd5dff1a.gif) | ![Screen Recording 2019-05-03 at 03 54 …

Replace current toggleHeader logic

---

README.md
src/README.md
src/commands.js
test/test-commands.js

`splitCell` has some limitation. 
Current implementation split the cell using the same cell type that the most top/left in the merge cells. 
This causes a merged cell with table header type to propagate to other cells when you split.
Solution:
This PR's propose a new `splitCell` api, where we are allowed to pass a function to get the **cell type**. The implementation is going to be the same as `splitCell` and we are going to rewrite `splitCell` to be created base on the new `splitCellWithType` using the default behaviour.

Allow split cell with custom cell types

---

src/util.js

Fix bug where cannot split cells when the selection is in the same depth as the cell but it's not a cell selection.
I tried to add a test case into the suite, but it wasn't possible. I couldn't replicate the conditions that cause a selection to have the same depth as the cell. You can simulate this scenario in our storybook:  https://atlaskit.atlassian.com/examples/editor/editor-core/full-page 
Creating a table with a merged cell and trying to split the cell with a media or gap cursor inside the cell.

Fix cell wrapping no checking in the current depth

---

index.d.ts

Function `fixTables` is export by `index.js`, by it's not included in `index.d.ts`. This PR fixes it.

Add fixTables into index.d.ts

---

src/index.js

Hi
My team and I are working on[ an editor](https://github.com/chanzuckerberg/czi-prosemirror) that has a different table-resizing behavior. In order to do that, we'd like to use some of the utility functions but unfortunately these function are not exported to `index.js` yet.
Our current workaround is to use a [forked version ](https://github.com/chanzuckerberg/prosemirror-tables/commits/add_export_v0_9_5) and that's not an ideal solution so we'd hope to merge the changes back to master then we'd continue to use the latest `prosemirror-table`.
Thanks.

Export `setAttr`, `pointsAtCell`, `tableNodeTypes` and `TableView` at `index.js`

---

index.d.ts
package.json
src/cellselection.js
src/commands.js
src/copypaste.js
src/fixtables.js
src/index.js
src/util.js
test/typescript/prosemirror-tables.ts
tsconfig.json

This includes the changes on: https://github.com/ProseMirror/prosemirror-tables/pull/108
And all the changes on master previous the breaking change. The idea is to release the changes on top of 0.x releases.

Export utils over 0.9.5

---

index.d.ts
src/cellselection.js
src/commands.js
src/copypaste.js
src/fixtables.js
src/index.js
src/util.js

I need to expose some internal utils. I required this to implement an iterator to get information of cells in a column:
```typescript
function cellsAtColumn*(rect: TableRect, col: number): Iterable<{
row: number,
from: number,
to: number,
hasMergedCells: boolean,
type: NodeType,
//......
}>
```
For big tables iterate twice to do an operation will be expensive. An iterator allows you to use the same loop to do your own logic.
The project has a restriction about using iterators, I guess we don't want to drop support on older browsers.

Expose internal utils

---

src/columnresizing.js

The current code assumes it will never do that, but that doesn't appear to be a valid assumption—a customer ran into a crash when the returned object is dereferenced.

Don't crash in edgeCell when posAtCoords returns null

---

src/copypaste.js
test/test-copypaste.js

There's a use case where `prosemirror-tables` produce a negative rowSpan on paste that breaks the whole page in Confluence. 
Steps to reproduce: 
1. in the table below, copy the first two rows
2. select the last row and paste the copied slice
This happens inside `handlePaste` that calls `clipCells`. We're simply adding a check to avoid negative rowSpans.

Fix clipCells to avoid negative rowSpan

---

package.json
test/test-typescript.js
tsconfig.json
yarn.lock

There is a [TS issue](https://github.com/ProseMirror/prosemirror-tables/pull/178) in the latest version, which didn't get caught by the CI pipeline. More detail: #178 
The direct reason is that `typings-tester` was not configured correctly (#177). However, `typings-tester` doesn't get any new version since 4 years ago. I don't want to use an unmaintained pacakge so I remove it in this PR.
By adding `strict: true` in `tsconfig.json`, we can use `yarn typecheck` to find out the TS issue. So we don't need `typings-tester` anyway.

Make typescript test stricter

---

index.d.ts
test/typescript/prosemirror-tables.ts

https://github.com/ProseMirror/prosemirror-tables/pull/160
The CellBookmark type added here was incorrect and the following error is fixed.
```
index.ts:25:43 - error TS2322: Type 'CellSelection' is not assignable to type 'Selection'.
The types of 'getBookmark().map' are incompatible between these types.
Type '(mapping: Mapping) => CellBookmark' is not assignable to type '(mapping: Mappable) => SelectionBookmark'.
Types of parameters 'mapping' and 'mapping' are incompatible.
Type 'Mappable' is missing the following properties from type 'Mapping': maps, from, to, slice, and 5 more.
1      let state = EditorState.create({ doc, selection: CellSelection.create(table, 0) });
```

fix CellBookmark typing

---

src/columnresizing.js

seems to be an issue in FireFox only where mousing over the editor there is possibility that the target.classList is undefined 
not sure how the target ends up being #text and not a dom element, and only in firefox. but adding a check the error goes away

check target.classList is not undefined

---

src/columnresizing.ts

I am pretty sure this logic was incorrect, and it was causing the column drag resize handle to be missing from an edge when a cell two over to the left was vertically merged.
Before the change:
After the change:

Fix column resize handle logic

---

src/commands.ts
test/commands.test.ts

the cell whose colspan  is 2 marked in the green box is inserted twice.
In this commit, I added a variable "seen" to the function removeRow to skip the cells have been processed

Fix deleteRow for cells with colspan greater than 1

---

src/columnresizing.ts

Simple change to support the case where the `NodeView` used to render table nodes is created separately from the `columnResizing` plugin. By setting `View` explicitly to a nullish value the `NodeView` is not registered with the plugin.

Make NodeView in columnResizing optional

---

src/cellselection.ts

Closes https://github.com/ProseMirror/prosemirror-tables/issues/250

fix: fix cell boundary selection cheap elimination

---

src/columnresizing.ts
src/tableview.ts

This PR separates `cellMinWidth` into `cellMinWidth` and `defaultCellMinWidth`.
With this, we can create new columns that are a bit wider (100px default) and have some "breathing space", while still have automatic (not fixed sizing). These columns can still be resized by the user to a width smaller than the initial "auto" width (`defaultCellMinWidth`) up to a minimum of `cellMinWidth`.
(Note: I think this is relevant only when your `table` is not set to 100% width)

feat: add new option `defaultCellMinWidth` for `columnResizing()`

---

src/columnresizing.ts
src/tableview.ts
style/tables.css

It turns out the approach taken in https://github.com/ProseMirror/prosemirror-tables/pull/253 was not supported well on safari. It doesn't support the `min-width` property on `col` elements.
This PR takes a new approach by setting the `min-width` on `<td>` and `<th>` elements directly. The selector makes sure this is only added when the cells don't have an explicit width (`colwidth`) set. We also needed to make sure the `min-width` is not set when we're actively resizing a column; because in this case, the cells will not have a `colwidth` yet as the resize action is "pending". To resolve this, we added a decoration to the cell nodes that are being resized.

fix: support defaultCellMinWidth in older Safari

---

src/columnresizing.ts
src/input.ts

Right now when the view is set to being uneditable (so `view.editable` returns `false`), the cell selection & resizing will be handled. That's not really expected behavior. We could argue about cell selections still being valid but I think cell resizing should not be possible when the view is not editable.
This PR fixes those issues by preventing those DOM events of being handled.
This pull request includes several changes to ensure that mouse event handlers only execute when the editor is editable.
* [`src/columnresizing.ts`](diffhunk://#diff-dc5d0fbef1c3d662f868f56a4aa568d1378610945029acffa4bb91635dd6f4eeR145-R147): Added checks in `handleMouseMove`, `handleMouseLeave`, and `handleMouseDown` functions to ensure that the editor is editable before handling any events. …

fix: disable resizing when the editor view is uneditable

---

src/fixtables.ts
src/tablemap.ts
test/fixtable.test.ts

For context, see https://github.com/ProseMirror/prosemirror/issues/1506

fix: remove zero sized tables via `fixTables`

---

src/schema.ts

Regarding: https://discuss.prosemirror.net/t/heads-up-xss-risk-in-domserializer/6572
Add support for [validate property](https://prosemirror.net/docs/ref/#model.AttributeSpec.validate) in schema.

feat: add validate support for schema
